import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  mainView: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  }, 
  appName: {
    position: "absolute",
    width: 280,
    fontSize: 50,
    top: 146,
    left: 70,
    color: '#004AAD',
  },
  logo: {
    position: "absolute",
    width: 250,
    height: 250,
    top: 240,
    left: 80,
  },
  text: {
    position: "absolute",
    width: 341,
    height: 102,
    left: 32,
    top: 535,
    FontFace: 'Inter',
    fontSize: 28,
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#666666",
  }, 
  startExploringButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    gap: 10,
    position: "absolute",
    width: 351,
    height: 68,
    left: 30,
    top: 713,
    backgroundColor: "#00B5F8",
    borderRadius: 6,
  },
  buttonText: {
    width: 114,
    height: 22,
    FontFace: 'Inter',
    fontSize: 16,
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#FFFFFF",
  },
  smallText: {
    width: 200,
    height: 25,
    FontFace: 'Inter',
    fontSize: 16,
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#0A0A0A",
    top: 400,
  }
});